# from https://github.com/ProjectPythia/pythia-foundations/blob/main/environment.yml
# BEM added ipyidv, rise Jan 2022
name: MPO624
channels:
  - conda-forge
dependencies:
  - cartopy
  - jupyterlab
  - matplotlib
  - numpy
  - pip
  - python=3.8
  - scipy
  - xarray
  - cfgrib
  - rise
  - metpy
  - siphon 
  - pip:
      - sphinx-pythia-theme
      - ipyidv
